# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 346beb06ceeb56903a99cf54eeca55f2f1a691306b3c9273262f0fe234c3717dbbeee0607b2859b7ed224287e4287dab80a07f7e2de4448765d022e604a7db0a

test:
  secret_key_base: 974e8337891846a966279d55766b9854ecca766b63202e80061ad0a9fa1b850514b4f12d14efbcc1b3b089f8a129baa4038d30abfba45222d7b4633461332e87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
